/* eslint-disable @typescript-eslint/no-var-requires */
const path = require("path");
const webpack = require("webpack");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const CopyWebpackPlugin = require("copy-webpack-plugin");

// Read from .env or environment variables at build time.
// In dev, BACKEND_BASE_URL defaults to http://localhost:3001.
const BACKEND_BASE_URL =
  process.env.BACKEND_BASE_URL || "http://localhost:3001";

/** @type {import("webpack").Configuration} */
module.exports = (env, argv) => {
  const isProd = argv?.mode === "production";
  const devServerPort = 3000;

  return {
    mode: isProd ? "production" : "development",
    devtool: isProd ? "source-map" : "inline-source-map",

    entry: {
      // Ribbon function command bundle (loaded via FunctionFile in manifest)
      commands: "./src/commands/commands.ts",
      // Dialog bundle
      dialog: "./src/dialog/dialog.ts",
      // Taskpane bundle (minimal placeholder)
      taskpane: "./src/taskpane/taskpane.ts",
    },

    output: {
      path: path.resolve(__dirname, "dist"),
      filename: "[name]/[name].bundle.js",
      clean: true,
    },

    resolve: {
      extensions: [".ts", ".tsx", ".js"],
    },

    module: {
      rules: [
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,
          use: {
            loader: "ts-loader",
            options: { transpileOnly: !isProd },
          },
        },
        {
          test: /\.css$/,
          use: ["style-loader", "css-loader"],
        },
      ],
    },

    plugins: [
      // Inject BACKEND_BASE_URL as a compile-time constant into bundles.
      new webpack.DefinePlugin({
        BACKEND_BASE_URL: JSON.stringify(BACKEND_BASE_URL),
      }),

      // Generate commands.html (host page for the function command bundle).
      new HtmlWebpackPlugin({
        filename: "commands/commands.html",
        template: "./src/commands/commands.html",
        chunks: ["commands"],
        inject: true,
      }),

      // Dialog page.
      new HtmlWebpackPlugin({
        filename: "dialog/dialog.html",
        template: "./src/dialog/dialog.html",
        chunks: ["dialog"],
        inject: false, // dialog.html loads its own script tag
      }),

      // Taskpane page.
      new HtmlWebpackPlugin({
        filename: "taskpane/taskpane.html",
        template: "./src/taskpane/taskpane.html",
        chunks: ["taskpane"],
        inject: false, // taskpane.html loads its own script tag
      }),

      // Copy static assets (icons, manifest).
      new CopyWebpackPlugin({
        patterns: [
          { from: "assets", to: "assets", noErrorOnMissing: true },
          { from: "manifest.xml", to: "manifest.xml" },
        ],
      }),
    ],

    devServer: {
      port: devServerPort,
      server: {
        // Office add-ins require HTTPS even in dev.
        // office-addin-dev-certs generates a localhost cert automatically.
        // Run: npx office-addin-dev-certs install
        type: "https",
        options: devCertOptions(),
      },
      headers: {
        // Required for Office.js dialog to load the page.
        "Access-Control-Allow-Origin": "*",
      },
      hot: true,
      static: {
        directory: path.resolve(__dirname, "dist"),
      },
    },
  };
};

/**
 * Returns the SSL certificate paths generated by office-addin-dev-certs.
 * The certs are stored in the user's home directory.
 */
function devCertOptions() {
  const os = require("os");
  const certDir = path.join(
    os.homedir(),
    ".office-addin-dev-certs"
  );
  try {
    return {
      cert: path.join(certDir, "localhost.crt"),
      key:  path.join(certDir, "localhost.key"),
      ca:   path.join(certDir, "ca.crt"),
    };
  } catch {
    // Certs not yet generated — run: npx office-addin-dev-certs install
    console.warn("[webpack] Dev certs not found. Run: npx office-addin-dev-certs install");
    return {};
  }
}
